### ISSUE TITLE
Log in with google on demo does not work.

### ISSUE THREAD

**Issue by rollermy** [davidbarrero38/Ionic-4-firebase#2]
**Describe the bug**
Error:
This domain (app-firebase-started.web.app) is not authorized to run this operation. Add it to the OAuth redirect domains list in the Firebase console -> Auth section -> Sign in method tab.

**To Reproduce**
1. Go to home page
2. Click on Login with google
3. Open dev console

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Brave

**Comment by dvidd** [comment]
Hi, this is because you are trying to use the key for firebase for your own project domain, in login auth in the firebase console you can see the domains that are auth to use the auth, to solve this problem or api keys in the src/app/firebase.ts file or change you configuration in firebase

**Comment by rollermy** [comment]
Hey, I get the error on the demo for this project at https://app-firebase-started.web.app
I understand that locally i would need to change out the keys.

**Comment by dvidd** [comment]
Yeah you where right, i add that domain to the list of authorized domains and know it works
